# easy_admin:
#    design:
#         form_theme:
#             - 'bootstrap_5_layout.html.twig'
#             - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
#     entities:
#         Campaign:
#             class: App\Entity\News
#             label: News
#             form:
#                 fields:
#                     - title
#                     - { property: 'content', type: 'fos_ckeditor'}