security:

    enable_authenticator_manager: true

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\User:
            algorithm: auto
    
    role_hierarchy:
            ROLE_ADMIN:       ROLE_USER
            ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        # mes_utilisateurs:
        #     memory:
        #         users:
        #             Alex:
        #                 password: pa$$
        #                 roles: [ 'ROLE_USER', 'ROLE_ADMIN']

        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

        

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        main:
            lazy: true
            form_login:
                login_path: login
                check_path: login
                default_target_path: /
                always_use_default_target_path: true
                use_referer: true

            logout:
                path: app_logout
            
    access_control:
         - { path: ^/admin, roles: ROLE_ADMIN }
       # - { path: ^/profile, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'